import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainLayout from "@/app/components/layout/main-layout";

const bosch = localFont({
  src: [
    {
      path: "../../public/fonts/bosch-regular.woff2",
      weight: "400",
      style: "regular",
    },
  ],
  variable: "--font-bosch",
});

const masonNeue = localFont({
  src: [
    {
      path: "../../public/fonts/mason-neue-medium.woff2",
      weight: "500",
      style: "medium",
    },
  ],
  variable: "--font-mason-neue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bosch.variable} ${masonNeue.variable} antialiased`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
